# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3d5fa7129fd17ef92b24dd913b1888161a2a4e0cfa3f3b60942f3c1a0988d7719fa0470c9fcf5d6896781f1ed2a1dca439ba2683a249538668454a1f0038100

test:
  secret_key_base: 87368f5d291cf2658085240cabdc22f3442e71cf7798c66fed6a492574eda6ff979bb2fa12a9a57ac26fa88cc08e7597c2666ce1772841a2929dba4fa2fbf1f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
